default: &default 
  adapter: mysql2 
  encoding: utf8 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> 
  username: root 
  password: 
  host: local

development: 
  <<: *default 
  database: furima_42504_development 
  adapter: mysql2 
  username: root 
  password: 
  host: localhost 

test: 
  <<: *default 
  database: furima_42504_test 
  adapter: mysql2 
  username: root 
  password: 
  host: localhost 

production: 
  <<: *default 
  database: furima_42504_production 
  username: furima_42504
  password: <%= ENV["FURIMA_42504_DATABASE_PASSWORD"] %> 
  adapter: postgresql 
  url: <%= ENV['DATABASE_URL'] %>